network:
  _target_: net.SimpleNet
  in_channels: ${coordinate_system.coordinate_system.in_channels}
  out_channels: ${coordinate_system.coordinate_system.out_channels}
  intermediate_channels: 64 #1024
  num_res_blocks: 8
  num_output_rows: ${datamodule.datamodule.num_output_rows}
  dilation: 3  ### 1
  kernel_size: 9 
  norm_type: 'instance'      # 'layer' #'batch'    # 'batch'  'layer'   'instance'
  #use_bn_norm: true
  stride: 1
  bias: true

  normalize_inside_of_network: false #true





# network:
#   _target_: net.SimpleNet
#   in_channels: ${coordinate_system.coordinate_system.in_channels}
#   out_channels: ${coordinate_system.coordinate_system.out_channels}
#   intermediate_channels: 64 #1024
#   num_res_blocks: 8
#   num_output_rows: ${datamodule.datamodule.num_output_rows}
#   dilation: 3  ### 1
#   kernel_size: 9 
#   use_bn_norm: true 
#   stride: 1
#   bias: true

#   normaize_inside_of_network: true  #False
